ServiceHost/Areas/Admin/Pages/Index.cshtml.cs
using _01_QueryManagement;
using _01_QueryManagement.Contracts.Permissions;
using CompanyManagement.Application.Contracts.Company;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoneyManagement.Application.Contracts.Money;
using UserManagement.Application.Contracts.User;
using UserManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages
{
    public class IndexModel : PageModel
    {
        public CompanyEdit command;
        private readonly ICompanyApplication _companyApplication;
        private readonly IUserApplication _userApplication;
        private readonly IMoneyApplication _moneyApplication;
        public PermissionQueryModel permissionQueryModels;
        private readonly IPermissionQueryModel _permissionQueryModel;
        public IndexModel(IUserApplication userApplication, ICompanyApplication companyApplication, IMoneyApplication moneyApplication, IPermissionQueryModel permissionQueryModel)
        {
            _userApplication = userApplication;
            _companyApplication = companyApplication;
            _moneyApplication = moneyApplication;
            _permissionQueryModel = permissionQueryModel;
        }
        public void OnGet()
        {
        }
        public IActionResult OnGetLogout()
        {
            _userApplication.Logout();
            return RedirectToPage("/Index");
        }
        public IActionResult OnGetCompanyEdit()
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            if (permissionQueryModels.ListUsers == UserPermissions.ListUsers)
            {
                var company = _companyApplication.GetViewModel().FirstOrDefault();
                ViewData["Email"] = "_@_._";
                command = new CompanyEdit()
                {
                    Name = company.Name,
                    Email = company.Email,
                    Id = company.Id,
                    Mobile = company.Mobile,
                    MoneyId = company.MoneyId,
                    Moneys = _moneyApplication.GetViewModel()
                };
                return Partial("Company/Index", command);
            }
            else
            {
                return Content("<script>window.location.href='/Index';</script>");
            }
        }
    }
}

ServiceHost/Pages/Company.cshtml.cs
using _0_Framework.Application;
using CompanyManagement.Application.Contracts.Company;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MoneyManagement.Application.Contracts.Money;

namespace ServiceHost.Pages
{
    public class CompanyModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public SelectList money;
        public bool IsSuccedded { get; set; }
        private readonly ICompanyApplication _companyApplication;
        private readonly IAuthHelper _authHelper;
        private readonly IMoneyApplication _moneyApplication;
        public CompanyModel(IAuthHelper authHelper, ICompanyApplication companyApplication, IMoneyApplication moneyApplication)
        {
            _authHelper = authHelper;
            _companyApplication = companyApplication;
            _moneyApplication = moneyApplication;
        }
        public IActionResult OnGet()
        {
            Response.Cookies.Delete(".AspNetCore.Cookies");
            var company = _companyApplication.GetViewModel();
            if (company.Count == 0)
            {
                ViewData["Email"] = "_@_._";
                money = new SelectList(_moneyApplication.GetViewModel(), "Id", "NameCountry");
                return Page();
            }
            else
            {
                return Redirect("./Register");
            }
        }
        public IActionResult OnPost(CompanyCreate command)
        {
            OperationResult result = _companyApplication.Create(command);
            if (result.IsSuccedded == true)
            {
                Message = result.Message;
                IsSuccedded = result.IsSuccedded;
                return Page();
            }
            else
            {
                Message = result.Message;
                IsSuccedded = result.IsSuccedded;
                return Page();
            }
        }
    }
}

ServiceHost/Areas/Admin/Pages/Company/Index.cshtml
@model CompanyManagement.Application.Contracts.Company.CompanyEdit
@{
    ViewData["title"] = "ویرایش کمپنی";
}
<div class="modal-header">
    <h4 class="modal-title">ویرایش کمپنی @Model.Name</h4>
    <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="/Index"><i class="fa fa-close"></i></a>
</div>

<form class="needs-validation" novalidate asp-page="/Index" asp-page-handler="CompanyEdit" method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="Name">نام کمپنی</label>
                    <input id="Name" type="text" class="form-control" required asp-for="Name">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="Mobile">شماره تماس</label>
                    <input id="Mobile" dir="ltr" type="text" class="form-control" asp-for="Mobile">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="input-email">ایمیل</label>
                    <input id="input-email" dir="ltr" type="text" placeholder="@ViewData["Email"]" class="form-control input-mask" asp-for="Email" data-inputmask="'alias': 'email'">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="MoneyId">پول اصلی</label>
                    <select id="MoneyId" class="form-control" required asp-for="MoneyId"
                            asp-items='new SelectList(Model.Moneys, "Id", "NameCountry")'>
                        <option disabled value="" selected="">پول ها ...</option>
                    </select>
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="form-group">
                    <label for="Logo" class="form-label">عکس</label>
                    <input type="file" class="form-control" name="Logo" accept=".ico">
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
        <div class="modal-footer">
            <button type="submit" class="btn btn-sm btn-icon btn-outline-success"><i class="fa fa-save"></i></button>
        </div>
    </div>
</form>