ServiceHost/Areas/Admin/Pages/Security/Users/Index.cshtml.cs
using _0_Framework.Application;
using _01_QueryManagement;
using _01_QueryManagement.Contracts.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserManagement.Application.Contracts.Role;
using UserManagement.Application.Contracts.User;
using UserManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages.Security.Users
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public UserSearchModel SearchModel;
        public List<UserViewModel> users;
        public SelectList Roles;
        public SelectList Users;
        public PermissionQueryModel permissionQueryModels;
        private readonly IPermissionQueryModel _permissionQueryModel;
        private readonly IRoleApplication _roleApplication;
        private readonly IUserApplication _userApplication;
        private readonly IAuthHelper _AuthHelper;
        public IndexModel(IUserApplication accountApplication, IRoleApplication roleApplication, IPermissionQueryModel permissionQueryModel, IAuthHelper authHelper)
        {
            _roleApplication = roleApplication;
            _userApplication = accountApplication;
            _permissionQueryModel = permissionQueryModel;
            _AuthHelper = authHelper;
        }
        public IActionResult OnGet(UserSearchModel searchModel)
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            if (permissionQueryModels.ListUsers == UserPermissions.ListUsers || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                Roles = new SelectList(_roleApplication.GetViewModel(), "Id", "NamePersian");
                Users = new SelectList(_userApplication.GetViewModel(), "Id", "FullName");
                users = _userApplication.Search(searchModel).Where(x => x.Status == true && x.Active == true).ToList();
                permissionQueryModels = _permissionQueryModel.GetUsers();
                return Page();
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public void OnPost(UserSearchModel searchModel)
        {
            Roles = new SelectList(_roleApplication.GetViewModel(), "Id", "NamePersian");
            Users = new SelectList(_userApplication.GetViewModel(), "Id", "FullName");
            users = _userApplication.Search(searchModel).Where(x => x.Status == true && x.Active == true).ToList();
            permissionQueryModels = _permissionQueryModel.GetUsers();
        }
        public IActionResult OnGetCreate()
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            if (permissionQueryModels.AddUsers == UserPermissions.AddUsers || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var command = new UserCreate
                {
                    Roles = _roleApplication.GetViewModel()
                };
                return Partial("./Create", command);
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public JsonResult OnPostCreate(UserCreate command)
        {
            var result = _userApplication.Create(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetRemoved()
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            if (permissionQueryModels.RemovedUsers == UserPermissions.RemovedUsers || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var commnd = new UserRemoved()
                {
                    UserRemoveds = _userApplication.GetViewModel().Where(x => x.Status == false).ToList()
                };
                return Partial("./Removed", commnd);
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public IActionResult OnGetActived()
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            var currentAccout = _AuthHelper.CurrentUserInfo();
            if (currentAccout.Id != currentAccout.Id || permissionQueryModels.ActivedUsers == UserPermissions.ActivedUsers || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var commnd = new UserRemoved()
                {
                    UserRemoveds = _userApplication.GetViewModel().Where(x => x.Active == false).ToList()
                };
                return Partial("./Actived", commnd);
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public IActionResult OnGetEdit(int id)
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            var currentAccout = _AuthHelper.CurrentUserInfo();
            if (currentAccout.Id == currentAccout.Id || permissionQueryModels.EditUser == UserPermissions.EditUser || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var account = _userApplication.GetDetails(id);
                account.Roles = _roleApplication.GetViewModel();
                return Partial("Edit", account);
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public JsonResult OnPostEdit(UserEdit command)
        {
            var result = _userApplication.Edit(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetChangePassword(int id)
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            var currentAccout = _AuthHelper.CurrentUserInfo();
            if (currentAccout.Id == currentAccout.Id || permissionQueryModels.ChangePasswordUser == UserPermissions.ChangePasswordUser || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var command = new ChangePassword { Id = id };
                return Partial("ChangePassword", command);
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            var result = _userApplication.ChangePassword(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetRemove(int id)
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            var currentAccout = _AuthHelper.CurrentUserInfo();
            if (currentAccout.Id != currentAccout.Id || permissionQueryModels.RemoveUser == UserPermissions.RemoveUser || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var commnd = new Messages()
                {
                    Href = "Remove",
                    Icon = "Question.webp",
                    Id = id,
                    Message = "میخواهید کاربر مورد نظر را حذف کنید ؟"
                };
                return Partial("./Message", commnd);
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public IActionResult OnPostRemove(int id)
        {
            _userApplication.Remove(id);
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetOff(int id)
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            var currentAccout = _AuthHelper.CurrentUserInfo();
            if (currentAccout.Id != currentAccout.Id || permissionQueryModels.ActiveUser == UserPermissions.ActiveUser || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var commnd = new Messages()
                {
                    Href = "Off",
                    Icon = "Question.webp",
                    Id = id,
                    Message = "میخواهید کاربر مورد نظر را غبر فعال کنید ؟"
                };
                return Partial("./Message", commnd);
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public IActionResult OnPostOff(int id)
        {
            _userApplication.Off(id);
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetOn(int id)
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            if (permissionQueryModels.ActiveUser == UserPermissions.ActiveUser || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var commnd = new Messages()
                {
                    Href = "On",
                    Icon = "Question.webp",
                    Id = id,
                    Message = "میخواهید کاربر مورد نظر را فعال کنید ؟"
                };
                return Partial("./Message", commnd);
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public IActionResult OnPostOn(int id)
        {
            _userApplication.On(id);
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetActivate(int id)
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            if (permissionQueryModels.RemoveUser == UserPermissions.RemoveUser || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                var commnd = new Messages()
                {
                    Href = "Activate",
                    Icon = "Question.webp",
                    Id = id,
                    Message = "میخواهید کاربر مورد نظر را بازیابی کنید ؟"
                };
                return Partial("./Message", commnd);
            }
            else
            {
                return Redirect("/Index");

ServiceHost/Areas/Admin/Pages/Security/Users/Level.cshtml.cs
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using _01_QueryManagement.Contracts.Permissions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.NetworkInformation;
using UserManagement.Application.Contracts.User;
using UserManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages.Security.Users
{
    [Authorize(Roles = Roles.Admin)]
    public class LevelModel : PageModel
    {
        public PermissionsCreate Command;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        public PermissionQueryModel permissionQueryModels;

        private readonly IUserApplication _userApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        private readonly IPermissionQueryModel _permissionQueryModel;
        public LevelModel(IUserApplication userApplication, IEnumerable<IPermissionExposer> exposers, IPermissionQueryModel permissionQueryModel)
        {
            _userApplication = userApplication;
            _exposers = exposers;
            _permissionQueryModel = permissionQueryModel;
        }
        public IActionResult OnGet(string slug)
        {
            permissionQueryModels = _permissionQueryModel.GetUsers();
            if (permissionQueryModels.LevelUser == UserPermissions.LevelUser || permissionQueryModels.AdminUsers == UserPermissions.AdminUsers)
            {
                Command = _userApplication.GetDetailsPer(slug);
                foreach (var exposer in _exposers)
                {
                    var exposedPermissions = exposer.Expose();
                    foreach (var (key, value) in exposedPermissions)
                    {
                        var group = new SelectListGroup { Name = key };
                        foreach (var permission in value)
                        {
                            var item = new SelectListItem(permission.Name, permission.Code.ToString())
                            {
                                Group = group
                            };

                            if (Command.MappedPermissions.Any(x => x.Code == permission.Code))
                                item.Selected = true;

                            Permissions.Add(item);
                        }
                    }
                }
                return Page();
            }
            else
            {
                return Redirect("/Index");
            }
        }
        public IActionResult OnPost(PermissionsCreate command)
        {
            var result = _userApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Security/Users/Actived.cshtml
@model UserManagement.Application.Contracts.User.UserRemoved
@{
    ViewData["title"] = "لیست کاربران غیرفعال شده";
}
<div class="modal-header">
    <h4 class="modal-title">لیست کاربران غیرفعال شده</h4>
    <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="./Index"><i class="fa fa-close"></i></a>
</div>

<div class="modal-body">
    <div class="table-responsive">
        <table class="table table-bordered table-hover display nowrap margin-top-10 w-p100 js-serial">
            <thead class="table-Primary">
                <tr>
                    <th class="text-center">نام مکمل</th>
                    <th class="text-center">نام کاربری</th>
                    <th class="text-center">عملیات</th>
                </tr>
            </thead>
            <tbody id="tbody">
                @foreach (var item in Model.UserRemoveds)
                {
                    <tr>
                        <td class="text-center">@item.FullName</td>
                        <td class="text-center">@item.UserName</td>
                        <td class="text-center">
                            <a class="btn btn-sm btn-icon btn-outline-danger" title="فعال کردن" href="#showmodal=@Url.Page("./Index", "On", new { id = item.Id })"><i class="mdi mdi-account-check"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ServiceHost/Areas/Admin/Pages/Security/Users/ChangePassword.cshtml
@model UserManagement.Application.Contracts.User.ChangePassword
@{
    ViewData["title"] = "رمز عبور جدید";
}
<div class="modal-header">
    <h4 class="modal-title">رمز عبور جدید</h4>
    <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="./Index"><i class="fa fa-close"></i></a>
</div>

<form class="needs-validation" novalidate asp-page="./Index" asp-page-handler="ChangePassword" method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="Password">رمز عبور</label>
                    <input id="Password" type="text" class="form-control" required asp-for="Password">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="RePassword">تکرار رمز عبور</label>
                    <input id="RePassword" type="text" class="form-control" required asp-for="RePassword">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="SecurityCod">کد امنیتی</label>
                    <input id="SecurityCod" dir="ltr" type="text" required class="form-control" asp-for="SecurityCod">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
        <div class="modal-footer">
            <button type="submit" class="btn btn-sm btn-icon btn-outline-success"><i class="fa fa-save"></i></button>
        </div>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Security/Users/Create.cshtml
@model UserManagement.Application.Contracts.User.UserCreate
@{
    ViewData["title"] = "ثبت کاربری جدید";
}
<div class="modal-header">
    <h4 class="modal-title">ثبت کاربری جدید</h4>
    <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="./Index"><i class="fa fa-close"></i></a>
</div>

<form class="needs-validation" novalidate asp-page="./Index" asp-page-handler="Create" method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="FullName">نام کامل</label>
                    <input id="Fullname" type="text" class="form-control" required name="FullName">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="UserName">نام کاربری</label>
                    <input id="Username" type="text" class="form-control" required name="UserName">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="Mobile">شماره تماس</label>
                    <input id="Mobile" dir="ltr" type="text" required class="form-control" name="Mobile">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="RoleId">وظیفه</label>
                    <select id="RoleId" class="form-control" required name="RoleId"
                            asp-items='new SelectList(Model.Roles, "Id", "NamePersian")'>
                        <option disabled value="" selected="">وظیفه ها ...</option>
                    </select>
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="Password">رمز عبور</label>
                    <input type="text" class="form-control" required id="Password" name="Password">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="SecurityCod">کد امنیتی</label>
                    <input type="text" class="form-control" required id="Password" name="SecurityCod">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label for="ProfilePhoto" class="form-label">عکس</label>
                    <input type="file" class="form-control" name="ProfilePhoto" accept=".webp">
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-sm btn-icon btn-outline-success"><i class="fa fa-save"></i></button>
        </div>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Security/Users/Edit.cshtml
@model UserManagement.Application.Contracts.User.UserEdit
@{
    ViewData["title"] = "ویرایش کاربر";
}
<div class="modal-header">
    <h4 class="modal-title">ویرایش کاربر @Model.FullName</h4>
    <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="./Index"><i class="fa fa-close"></i></a>
</div>

<form class="needs-validation" novalidate asp-page="./Index" asp-page-handler="Edit" method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="FullName">نام کامل</label>
                    <input id="Fullname" type="text" class="form-control" required asp-for="FullName">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="UserName">نام کاربری</label>
                    <input id="Username" type="text" class="form-control" required asp-for="UserName">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="Mobile">شماره تماس</label>
                    <input id="Mobile" dir="ltr" type="text" required class="form-control" asp-for="Mobile">
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="form-label" for="RoleId">وظیفه</label>
                    <select id="RoleId" class="form-control" required asp-for="RoleId"
                            asp-items='new SelectList(Model.Roles, "Id", "NamePersian")'>
                        <option disabled value="" selected="">وظیفه ها ...</option>
                    </select>
                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="form-group">
                    <label for="ProfilePhoto" class="form-label">عکس</label>
                    <input type="file" class="form-control" name="ProfilePhoto" accept=".webp">
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
        <div class="modal-footer">
            <button type="submit" class="btn btn-sm btn-icon btn-outline-success"><i class="fa fa-save"></i></button>
        </div>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Security/Users/Level.cshtml
@page "{slug}"
@model ServiceHost.Areas.Admin.Pages.Security.Users.LevelModel
@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت کاربران";
}
<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between bb-1 border-info">
                    <div class="header-title">
                        <a class="btn btn-sm btn-icon btn-outline-success mx-2" title="لیست کاربران" asp-page="./Index"><i class="mdi mdi-view-sequential"></i></a>
                        <span class="card-title mx-2">سطح دسترسی - @Model.Command.FullName</span>
                    </div>
                </div>
                <div class="card-body">
                    <form class="needs-validation" novalidate method="post">
                        <div class="modal-body">
                            <div class="row">
                                <div class="form-group">
                                    <label class="form-label" for="Permissions">سطح دسترسی</label>
                                    <select required asp-for="Command.Permissions" asp-items="Model.Permissions" class="multi-select" multiple="multiple" id="my_multi_select3">
                                    </select>
                                    <div class="invalid-feedback">اطلاعات باید وارد شود !</div>
                                </div>
                            </div>
                            <input type="hidden" asp-for="Command.Id" value="@Model.Command.Id" />
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-sm btn-icon btn-outline-success"><i class="fa fa-save"></i></button>
                                <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="./Index"><i class="fa fa-close"></i></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@section Css
    {
    <link href="~/Theme/assets/vendor_components/jquery-multi-select/multi-select.css" rel="stylesheet" type="text/css" />
}

    @section Scripts
    {
    <script type="text/javascript" src="~/Theme/assets/vendor_components/jquery-multi-select/jquery.multi-select.js"></script>
    <script type="text/javascript" src="~/Theme/assets/vendor_components/jquery-multi-select/jquery.quicksearch.js"></script>

    <script>
        jQuery(document).ready(function () {
            $('#my_multi_select3').multiSelect({
                selectableOptgroup: true,
                selectableHeader:
                    "<input type='text' class='form-control col-sm-4 search-input' autocomplete='off' placeholder='جستجو...'>",
                selectionHeader:
                    "<input type='text' class='form-control col-sm-4 search-input' autocomplete='off' placeholder='جستجو...'>",
                afterInit: function (ms) {
                    var that = this,
                        $selectableSearch = that.$selectableUl.prev(),
                        $selectionSearch = that.$selectionUl.prev(),
                        selectableSearchString =
                            '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                        selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';

                    that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                        .on('keydown',
                            function (e) {
                                if (e.which === 40) {
                                    that.$selectableUl.focus();
                                    return false;
                                }
                            });

                    that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                        .on('keydown',
                            function (e) {
                                if (e.which == 40) {
                                    that.$selectionUl.focus();
                                    return false;
                                }
                            });
                },
                afterSelect: function () {
                    this.qs1.cache();
                    this.qs2.cache();
                },
                afterDeselect: function () {
                    this.qs1.cache();
                    this.qs2.cache();
                }
            });
        });
    </script>
}

ServiceHost/Areas/Admin/Pages/Security/Users/Message.cshtml
@model _01_QueryManagement.Messages
@{
}
<form class="needs-validation" novalidate asp-page="./Index" asp-page-handler="@Model.Href" method="post">
    <div class="modal-body">
        <div class="row">
            <div class="form-group col-sm-12 text-center">
                <img class="col-sm-4" src="~/Uploader/Images/@Model.Icon" alt="icon" style="width:55px">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-12 text-center">
                <label class="form-check-label" for="Receipt">@Model.Message</label>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
        <div class="row text-center">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-sm btn-icon btn-outline-success"><i class="fa fa-check"></i></button>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="./Index"><i class="fa fa-close"></i></a>
            </div>
        </div>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Security/Users/Removed.cshtml
@model UserManagement.Application.Contracts.User.UserRemoved
@{
    ViewData["title"] = "لیست کاربران حذف شده";
}
<div class="modal-header">
    <h4 class="modal-title">لیست کاربران حذف شده</h4>
    <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="./Index"><i class="fa fa-close"></i></a>
</div>

<div class="modal-body">
    <div class="table-responsive">
        <table class="table table-bordered table-hover display nowrap margin-top-10 w-p100 js-serial">
            <thead class="table-Primary">
                <tr>
                    <th class="text-center">نام مکمل</th>
                    <th class="text-center">نام کاربری</th>
                    <th class="text-center">عملیات</th>
                </tr>
            </thead>
            <tbody id="tbody">
                @foreach (var item in Model.UserRemoveds)
                {
                    <tr>
                        <td class="text-center">@item.FullName</td>
                        <td class="text-center">@item.UserName</td>
                        <td class="text-center">
                            <a class="btn btn-sm btn-icon btn-outline-primary" title="بازیابی" href="#showmodal=@Url.Page("./Index", "Activate", new { id = item.Id })"><i class="mdi mdi-account-convert"></i></a>
                            <a class="btn btn-sm btn-icon btn-outline-danger" title="حذف کامل" href="#showmodal=@Url.Page("./Index", "Delete", new { id = item.Id })"><i class="mdi mdi-account-remove"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ServiceHost/Areas/Admin/Pages/Security/Users/Saved.cshtml
@model UserManagement.Application.Contracts.User.UserViewModel
@{
    ViewData["title"] = "ثبت کننده کاربر";
}
<div class="modal-header">
    <h4 class="modal-title">ثبت کننده کاربر  - @Model.FullName</h4>
    <a class="btn btn-sm btn-icon btn-outline-warning" asp-page="./Index"><i class="fa fa-close"></i></a>
</div>

<form class="needs-validation">
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="form-label" for="User_Name">نام ثبت کننده</label>
                    <input id="User_Name" readonly type="text" class="form-control" required asp-for="User_Name">
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="form-label" for="SaveDate">تاریخ ثبت</label>
                    <input id="SaveDate" readonly type="text" class="form-control" required asp-for="SaveDate">
                </div>
            </div>
        </div>
    </div>
</form>